name: PRCMoney
main: kr.eme.prcMoney.PRCMoney
version: 1.0.4
api-version: 1.21
depend:
  - PRCMission
commands:
  ep:
      usage: /ep
      aliases: EP
  token:
    usage: /token <금액> [수량]
    aliases: 수표
