name: SemiMoneyGlobal
main: kr.eme.semiMoneyGlobal.SemiMoneyGlobal
version: 1.0
api-version: 1.21
commands:
  ep:
      usage: /ep
      aliases: EP
  cheque:
    usage: /cheque or /수표
    aliases: 수표